apiVersion: v1
kind: ServiceAccount
metadata:
  name: nutriai-service-account
  namespace: nutriai
  labels:
    app.kubernetes.io/part-of: nutriai
  annotations:
    azure.workload.identity/client-id: "your-identity-client-id"
